apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-tls
spec:
  provider: azure
  secretObjects:
  - secretName: ingress-tls-csi
    type: kubernetes.io/tls
    data: 
    - objectName: helloworld
      key: tls.key
    - objectName: helloworld
      key: tls.crt
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true"
    userAssignedIdentityID: "XXXXX-xxxx-XXXX-xxxx-XXXXXXXX"
    keyvaultName: akspublic-deve-kv
    objects: |
      array:
        - |
          objectName: helloworld
          objectType: secret
    tenantId: "XXXXX-xxxx-XXXX-xxxx-XXXXXXXX"
